version: '3'
services:
  langchain-frontend:
    image: langchain/langchainplus-frontend:latest
    ports:
      - 80:80
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend
    build:
      context: frontend-react/.
      dockerfile: Dockerfile
  langchain-backend:
    image: langchain/langchainplus-backend:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - 8000:8000
    depends_on:
      - langchain-db
    build:
      context: backend/.
      dockerfile: Dockerfile
  langchain-db:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
